/* Generated by tools/convert.js — edit freely, it is not regenerated. */
window.KA_CONFIG = {
  title: "For those who have a moderate computer",

  /* The size the program ran at on Khan Academy. The header comment offers
     800 / 900 / 1000-wide variants; this is the one Corin plays at. */
  width: 1000,
  height: 600,

  /* Khan Academy audio. Files go in sounds/<name>.mp3 ; leave enabled and
     the game simply stays silent when a file is missing. */
  sound: true
};
